### PR TITLE
sorter: sorting for REST API

### PR DESCRIPTION
**Pull request by lnielsen**
* (addresses inveniosoftware/invenio-search#52)

* (addresses inveniosoftware/invenio-search#53)

### CODE REVIEW

**Comment by lnielsen** [comment]
sort field names has to be fixed from "field/-field" to "field:asc/fied:desc" (impacts invenio-search-js)

**Comment by lnielsen** [comment]
Ping @egabancho - ready for review.

**Comment by egabancho** [comment]
Should we also update the example app? otherwise :shipit:

**Comment by lnielsen** [comment]
I've opened an issue for it #37 :-) Will do it as part of the facets :-)

**Pull request merged**
